#!/bin/bash

#Web Sweep
for ips in {101..106}; do (curl -m 1 192.168.69.$ips >/dev/null)
	if [ $? -eq 0 ]
	then
		content=$(awk -F '#' '{print $2}')
		echo $content
		if [ $content -eq $ips ]
		then
		points=5;
		current=$(cat team$ips);
		echo "Team "$ips" earned "$points" points";
		expr $current + $points > team$ips
		fi
	else
		echo "Team "$ips" metasploit web is down";
	fi
done
